Lesson 7: Add redirecting middleware
S7rife/fefu_backend_2_3 pull request #6
Opened 2021-11-02 13:59 UTC by S7rife

2021-11-04 06:21 UTC, chrn-feip requested changes

2021-11-04 06:21 UTC, chrn-feip commented on app/Models/News.php
> + * @property Carbon $created_at
Ещё забыли другие атрибуты модели.

2021-11-04 06:21 UTC, chrn-feip commented on app/Console/Commands/ChangeNewsSlug.php
> +            Redirect::where('old_slug', $newSlug)->delete();
Учтите, что таблица редиректов не знает ничего про сущности, там old_slug и new_slug - это часть URL без протокола и домена, т.е. в случае новостей там будут ссылки вида /news/<slug> в новом и старом слаге. В таблице редиректов могут быть аналогичные пары для других маршрутов. А в таблице новости слаг - это часть URL без префикса маршрута. Т.е. тут надо искать по слагу, который  генерируется из маршрута, но без базового  URL. А в модели новости, в save, записывать в поля слагов аналогичные значения.

2021-11-04 06:21 UTC, chrn-feip commented on app/Http/Middleware/RedirectFromOldSlug.php
> +        $redirect = Redirect::where('old_slug', $url)
Тут как раз не надо вырезать префикс, потому что он будет внутри значений в таблице редиректов. И ваш посредник вообще не будет знать (а ему и не нужно), что дело именно в новости. Он с таким же успехов сделает редирект на какие угодно заданные URL.

2021-11-04 06:21 UTC, chrn-feip commented on app/Http/Middleware/RedirectFromOldSlug.php
> +        if ($redirect !== null)
Вам нужен цикл while, чтобы за один вызов этого посредника найти нужный адрес. Никто не говорит, что у вас будет только 2 или 3 итерации смены слагов в таблице.

2021-11-04 06:21 UTC, chrn-feip commented on app/Http/Middleware/RedirectFromOldSlug.php
> +                return redirect()->route('news_item', ['slug' => $redirect2->new_slug]);
Редирект не на маршрут, а на то, что в new_slug модели редиректа, там внутри уже будет префикс маршрута, который вы добавите в сохранение.

2021-11-04 06:22 UTC, chrn-feip commented
![image](https://user-images.githubusercontent.com/40585429/140267250-66dd2706-e7c6-4d68-a644-9f1a7c8bdf5e.png)
Это условие:, вероятно, не так поняли. Потому что его я не видела, но ваш checkSame делает не то, что тут требуется. Нужно взять значения аргументов команды и по ним найти запись в таблице редиректов, в которой old_slug равен oldSlug, а new_slug равен newSlug. Чтобы не создавать дубликаты в таблице редиректов.

2021-11-05 08:24 UTC, chrn-feip requested changes

2021-11-05 08:24 UTC, chrn-feip commented on app/Models/News.php
> + * @property string $description
Опциональное

2021-11-05 08:24 UTC, chrn-feip commented on app/Http/Middleware/RedirectFromOldSlug.php
> +        while ($redirect !== null)
Нет.  Вам не просто нужно заменить свой if на while. Нужно написать его таким образом, чтобы в цикле while происходил поиск самой свежей записи редиректа, которая подходит условиям поиска (слаг, дата и т.п.). В цикле нашли запись-таргет, за циклом проверили на null и есть она есть, то сделали редирект. Если нет - вызвали next.

2021-11-05 08:24 UTC, chrn-feip commented on app/Models/News.php
> +            $redirect->old_slug = 'news/'.$oldSlug;
Надёжнее использовать не хардкод префикса, а прямо route по имени, но исключая базовый url (протокол и домен). Никто не гарантирует, что префикс будет всегда такой.

2021-11-05 08:24 UTC, chrn-feip commented on app/Console/Commands/ChangeNewsSlug.php
> +            Redirect::where('old_slug', 'news/'.$newSlug)->delete();
То же самое про хардкод префикса

2021-11-05 08:24 UTC, chrn-feip commented on app/Console/Commands/ChangeNewsSlug.php
> +        $checkSame = Redirect::where('old_slug', 'news/'.$oldSlug)
То же самое про хардкод префикса

2021-11-05 08:39 UTC, S7rife commented on app/Models/News.php
> + * @property string $description
не понимаю

2021-11-05 08:44 UTC, chrn-feip commented on app/Models/News.php
> + * @property string $description
![image](https://user-images.githubusercontent.com/40585429/140482843-7e99c38b-0ef8-41be-bf23-e47e8de18f6f.png)

поле краткого описания новости может быть не только строкой, но null

2021-11-05 09:44 UTC, chrn-feip requested changes

2021-11-05 09:44 UTC, chrn-feip commented on app/Http/Middleware/RedirectFromOldSlug.php
> +            echo $slug = $redirect->new_slug;
Отладочный вывод не забывайте удалять после тестирования. Я про echo. Само определение переменной оставляйте.

2021-11-05 09:59 UTC, merged